### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [SSaapon/colmar-academy#4]
Grade: Meets expectations

Summary:
Overall, awesome work on this final project.  I like you use of semantic HTML elements, your use of locally stored media, your use of responsive concepts, and your styling choices (particularly the colors your chose).

A couple things to work on here would be: 1. making sure you use descriptive `alt` attributes for each of your `<img>` elements and 2. using group selectors for any repeated styles in your CSS.

Next, I challenge you to build more pages for this site.  What does a sign in page look like? What about a course page?  Building these extra pages will add some complexity and is a challenge I think you are ready for based on your work here!

**Comment by SSaapon** [comment]
Thanks for the feedback.
